export const WEEK_DAYS = [
  { label: '일', color: 'text-[#FF3D00]' },
  { label: '월', color: 'text-[#A8A19A]' },
  { label: '화', color: 'text-[#A8A19A]' },
  { label: '수', color: 'text-[#A8A19A]' },
  { label: '목', color: 'text-[#A8A19A]' },
  { label: '금', color: 'text-[#A8A19A]' },
  { label: '토', color: 'text-[#015DE7]' },
];

export const CELLS = [
  { day: 29, muted: true },
  { day: 30, muted: true, events: [{ label: '민준 코로나 건사', color: 'bg-[#5AA7FF]' }] },
  { day: 1 },
  { day: 2 },
  { day: 3, events: [{ label: '하나 두통 멀미', color: 'bg-[#FF8763]' }] },
  { day: 4 },
  { day: 5, events: [{ label: '지원 처방전 발급', color: 'bg-[#FFC721]' }] },
  { day: 6 },
  { day: 7, events: [{ label: '하나 진단서 발급', color: 'bg-[#FF8763]' }] },
  { day: 8, events: [{ label: '하나 진단서', color: 'bg-[#FF8763]' }] },
  { day: 9 },
  {
    day: 10,
    selected: true,
    events: [
      {
        label: '민준 예방접종',
        color: 'bg-[#5AA7FF]',
        location: '서울시청 부속의원',
        memo: '',
        time: '오후 12:00',
      },
      { label: '하나 진단서 발급', color: 'bg-[#FF8763]' },
      { label: '지원 소아과 방문', color: 'bg-[#FFC721]' },
    ],
  },
  { day: 11 },
  { day: 12 },
  { day: 13 },
  { day: 14 },
  { day: 15 },
  { day: 16 },
  { day: 17 },
  { day: 18 },
  { day: 19 },
  { day: 20, events: [{ label: '지원 교정 검사', color: 'bg-[#FFC721]' }] },
  { day: 21 },
  { day: 22 },
  { day: 23 },
  { day: 24 },
  { day: 25, events: [{ label: '지원 사랑니 발치', color: 'bg-[#FFC721]' }] },
  { day: 26 },
  { day: 27 },
  { day: 28, muted: true, events: [{ label: '하나 엑스레이', color: 'bg-[#FF8763]' }] },
  { day: 29, muted: true },
  { day: 30, muted: true },
  { day: 31, muted: true },
];
